### ISSUE TITLE
https://github.com/fickryiman/react-redux-group-project

### ISSUE THREAD

**Issue by fickryiman** [fickryiman/react-redux-group-project#50]
Kanban Board: https://github.com/fickryiman/react-redux-group-project/projects/2

We are 2 people in this react redux group project, with the below details:
Student A: https://github.com/fickryiman
Student B: https://github.com/ehmaddd

**Comment by BregornOriginal** [comment]
Hi @fickryiman and @ehmaddd 

Your project is complete!  There is nothing else to say other than... it's time to merge it 

Congratulations! 

![giphy (7)](https://github.com/fickryiman/react-redux-group-project/assets/93630700/12ff878c-77a8-4e64-962b-7b2c6d128239)

## Highlights

✅ Good work on setup the Kanban board


## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)
